[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@chainlink/local/=lib/chainlink-local/"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./img" },
]

[fmt]
line_length = 180
format_on_save = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[lint]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
